baseURL = "https://www.jonathanluckyyap.my.id/"
languageCode = "en-us"
title = "Jonathan Lucky Yap - Portfolio"
name = "Simple Dev Portfolio"
license = "MIT"
licenselink = "https://https://github.com/xinweilau/simple-dev-portfolio/blob/main/LICENSE"
description = "Simple portfolio website with TailwindCSS"
homepage = "https://jonathanluckyyap.my.id/"
tags = ["Hugo", "TailwindCSS", "developer", "theme"]
features = []
min_version = "0.41.0"

[author]
  name = "Jonathan Lucky Yap"
  homepage = "https://jonathanluckyyap.my.id/"
